version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://stockuser:StockPass2024!@host.docker.internal:5432/stockwatchlist
      - TZ=America/Chicago
      - FINNHUB_API_KEY=${FINNHUB_API_KEY:-demo}
      - SCHWAB_CLIENT_ID=${SCHWAB_CLIENT_ID}
      - SCHWAB_CLIENT_SECRET=${SCHWAB_CLIENT_SECRET}
      - SCHWAB_REFRESH_TOKEN=${SCHWAB_REFRESH_TOKEN}
      - SCHWAB_BASE_URL=${SCHWAB_BASE_URL:-https://api.schwabapi.com}
      # Technical compute tail/window settings
      - TECH_TAIL_DAYS=${TECH_TAIL_DAYS:-800}
      - TECH_BUFFER_DAYS=${TECH_BUFFER_DAYS:-30}
      - TECH_MIN_ROWS=${TECH_MIN_ROWS:-252}
    volumes:
      - ./backend:/app
      - C:\Users\raghu\Downloads:/downloads
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - TZ=America/Chicago
      - VITE_API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
