version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./stock_watchlist.db
      - TZ=America/Chicago
      - FINNHUB_API_KEY
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - TZ=America/Chicago
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: alpine:latest
    command: ["sh", "-c", "mkdir -p /data && tail -f /dev/null"]
    volumes:
      - backend_data:/data
    networks:
      - app-network

volumes:
  backend_data:

networks:
  app-network:
    driver: bridge