version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: stockuser
      POSTGRES_PASSWORD: stockpass123
      POSTGRES_DB: stockwatchlist
      # Performance optimizations for large data imports
      POSTGRES_SHARED_PRELOAD_LIBRARIES: pg_stat_statements
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    command: >
      postgres -c shared_buffers=256MB
               -c effective_cache_size=1GB
               -c maintenance_work_mem=128MB
               -c checkpoint_completion_target=0.9
               -c wal_buffers=16MB
               -c default_statistics_target=100
               -c random_page_cost=1.1
               -c effective_io_concurrency=200
               -c work_mem=4MB
               -c min_wal_size=1GB
               -c max_wal_size=4GB
               -c max_connections=200

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://stockuser:stockpass123@postgres:5432/stockwatchlist
      - TZ=America/Chicago
      - FINNHUB_API_KEY=${FINNHUB_API_KEY:-demo}
      - SCHWAB_CLIENT_ID=${SCHWAB_CLIENT_ID}
      - SCHWAB_CLIENT_SECRET=${SCHWAB_CLIENT_SECRET}
      - SCHWAB_REFRESH_TOKEN=${SCHWAB_REFRESH_TOKEN}
      - SCHWAB_BASE_URL=${SCHWAB_BASE_URL:-https://api.schwabapi.com}
      # Technical compute tail/window settings
      - TECH_TAIL_DAYS=${TECH_TAIL_DAYS:-800}
      - TECH_BUFFER_DAYS=${TECH_BUFFER_DAYS:-30}
      - TECH_MIN_ROWS=${TECH_MIN_ROWS:-252}
    volumes:
      - ./backend:/app
      - C:\Users\raghu\Downloads:/downloads
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres

  external-apis:
    build: ./external-apis
    ports:
      - "8003:8003"
    environment:
      - TZ=America/Chicago
      - FINNHUB_API_KEY=${FINNHUB_API_KEY:-demo}
      - SCHWAB_CLIENT_ID=${SCHWAB_CLIENT_ID}
      - SCHWAB_CLIENT_SECRET=${SCHWAB_CLIENT_SECRET}
      - SCHWAB_REFRESH_TOKEN=${SCHWAB_REFRESH_TOKEN}
      - SCHWAB_BASE_URL=${SCHWAB_BASE_URL:-https://api.schwabapi.com}
    volumes:
      - ./external-apis:/app
    networks:
      - app-network

  jobs-service:
    build: ./jobs-service
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=postgresql://stockuser:stockpass123@postgres:5432/stockwatchlist
      - TZ=America/Chicago
      - TIMEZONE=America/Chicago
      - BACKEND_URL=http://backend:8000
      - EXTERNAL_APIS_URL=http://external-apis:8003
      - KEEP_JOB_HISTORY=5
      - TTL_CLEANUP_DAYS=30
      - MARKET_OPEN_HOUR=9
      - MARKET_CLOSE_HOUR=16
    volumes:
      - ./jobs-service:/app
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - external-apis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - TZ=America/Chicago
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - backend
      - external-apis
      - jobs-service

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
