version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/stock_watchlist_clean.db
      - TZ=America/Chicago
      - FINNHUB_API_KEY=${FINNHUB_API_KEY:-demo}
    volumes:
      - ./backend:/app
      - C:\Users\raghu\Downloads:/downloads
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - TZ=America/Chicago
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge