"""Add company profile fields to watchlist items

Revision ID: 001_add_company_profile_fields
Revises: 
Create Date: 2024-01-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '001_add_company_profile_fields'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_items', sa.Column('sector', sa.String(length=100), nullable=True))
    op.add_column('watchlist_items', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('watchlist_items', sa.Column('market_cap', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist_items', 'market_cap')
    op.drop_column('watchlist_items', 'industry')
    op.drop_column('watchlist_items', 'sector')
    # ### end Alembic commands ###